const bancoPreguntas = {
    // 50 PREGUNTAS: Sustentabilidad Base (Nivel 1 y 2)
    base: [
        { lvl: 1, cat: "FUTBOL", q: "¿Qué se ponen los porteros en las manos?", a: "Guantes" },
        { lvl: 1, cat: "OCÉANO", q: "¿Cuál es el animal más grande del mundo?", a: "Ballena Azul" },
        { lvl: 1, cat: "ECOLOGÍA", q: "¿Qué es el reciclaje?", a: "Transformar residuos en nuevos productos" },
        { lvl: 1, cat: "PLANETA", q: "¿Cuál es el símbolo químico del agua?", a: "H2O" },
        { lvl: 1, cat: "MUNDIAL", q: "¿Cada cuántos años se juega el mundial?", a: "4" },
        { lvl: 1, cat: "ECOLOGÍA", q: "¿Qué gas absorben los árboles?", a: "Dióxido de carbono" },
        { lvl: 1, cat: "FUTBOL", q: "¿Cuántos jugadores hay por equipo en la cancha?", a: "11" },
        { lvl: 1, cat: "OCÉANO", q: "¿Qué porcentaje de la Tierra es agua?", a: "70 por ciento" },
        { lvl: 1, cat: "ECOLOGÍA", q: "¿Qué es el compostaje?", a: "Transformar residuos orgánicos en abono" },
        { lvl: 1, cat: "MUNDIAL", q: "¿En qué continente fue el mundial 2010?", a: "África" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es una huella de carbono?", a: "Medida del impacto de gases de efecto invernadero" },
        { lvl: 2, cat: "OCÉANO", q: "¿Cómo se llama la capa más profunda del mar?", a: "Zona Abisal" },
        { lvl: 2, cat: "MUNDIAL", q: "¿Quién ganó el mundial de México 86?", a: "Argentina" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué significa las 3R?", a: "Reducir Reutilizar y Reciclar" },
        { lvl: 2, cat: "PLANETA", q: "¿Qué capa nos protege de los rayos UV?", a: "Capa de ozono" },
        { lvl: 2, cat: "FUTBOL", q: "¿Qué dura un partido normal sin tiempos extra?", a: "90 minutos" },
        { lvl: 2, cat: "OCÉANO", q: "¿Cuál es el océano más grande?", a: "Pacífico" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es la biodiversidad?", a: "Variedad de seres vivos" },
        { lvl: 2, cat: "MUNDIAL", q: "¿En qué país se jugó el mundial de 2014?", a: "Brasil" },
        { lvl: 2, cat: "PLANETA", q: "¿Qué es el calentamiento global?", a: "Aumento de la temperatura terrestre" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué tipo de energía es el sol?", a: "Renovable" },
        { lvl: 2, cat: "FUTBOL", q: "¿Quién es el máximo goleador histórico?", a: "Cristiano Ronaldo" },
        { lvl: 2, cat: "OCÉANO", q: "¿Qué es el plancton?", a: "Organismos microscópicos acuáticos" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es un ecosistema?", a: "Comunidad de seres vivos y su medio" },
        { lvl: 2, cat: "MUNDIAL", q: "¿Cuántas veces ha ganado Brasil el mundial?", a: "5" },
        { lvl: 2, cat: "PLANETA", q: "¿Qué es la deforestación?", a: "Eliminación de bosques" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es la energía eólica?", a: "Energía del viento" },
        { lvl: 2, cat: "FUTBOL", q: "¿Qué es el VAR?", a: "Video Arbitraje" },
        { lvl: 2, cat: "OCÉANO", q: "¿Qué son los corales?", a: "Animales marinos" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es el cambio climático?", a: "Variación del clima terrestre" },
        { lvl: 2, cat: "MUNDIAL", q: "¿Qué selección es conocida como La Roja?", a: "España" },
        { lvl: 2, cat: "PLANETA", q: "¿Qué es la fotosíntesis?", a: "Proceso de crear energía de plantas" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué material tarda más en degradarse?", a: "Plástico" },
        { lvl: 2, cat: "FUTBOL", q: "¿Qué es un fuera de juego?", a: "Posición irregular" },
        { lvl: 2, cat: "OCÉANO", q: "¿Qué es una marea?", a: "Cambio de nivel del mar" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es el efecto invernadero?", a: "Retención de calor en la atmósfera" },
        { lvl: 2, cat: "MUNDIAL", q: "¿Qué país ganó en 2018?", a: "Francia" },
        { lvl: 2, cat: "PLANETA", q: "¿Cuál es el gas principal de la atmósfera?", a: "Nitrógeno" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es la sustentabilidad?", a: "Satisfacer necesidades sin dañar el futuro" },
        { lvl: 2, cat: "FUTBOL", q: "¿Quién organiza los mundiales?", a: "FIFA" },
        { lvl: 2, cat: "OCÉANO", q: "¿Qué es una fosa marina?", a: "Depresión profunda en el fondo" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es la contaminación?", a: "Introducción de sustancias dañinas" },
        { lvl: 2, cat: "MUNDIAL", q: "¿En qué país fue el mundial de 2006?", a: "Alemania" },
        { lvl: 2, cat: "PLANETA", q: "¿Qué es la capa de hielo?", a: "Región congelada en los polos" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es el ahorro energético?", a: "Reducir consumo de electricidad" },
        { lvl: 2, cat: "FUTBOL", q: "¿Qué color de tarjeta es expulsión?", a: "Roja" },
        { lvl: 2, cat: "OCÉANO", q: "¿Qué es una corriente marina?", a: "Movimiento de masas de agua" },
        { lvl: 2, cat: "ECOLOGÍA", q: "¿Qué es la huella hídrica?", a: "Uso de agua para productos" },
        { lvl: 2, cat: "MUNDIAL", q: "¿Qué equipo ganó el mundial de 1970?", a: "Brasil" },
        { lvl: 2, cat: "PLANETA", q: "¿Qué es la biosfera?", a: "Capa donde hay vida" }
    ],
    legend: [],
    ocean: []
};